/run/initialize
/vis/open OGL 
/vis/drawVolume
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate
/vis/modeling/trajectories/create/drawByParticleID
/vis/scene/add/hits
/vis/viewer/set/background white 1.0
/vis/viewer/set/viewpointVector 1 0 0
/vis/viewer/set/autoRefresh true
/process/optical/EnableScintillation true
/process/optical/EnableAbsorption     true
/process/optical/EnableRayleigh       true
/process/optical/EnableBoundary       true
