/pgai/source/spotSize 65 mm
/pgai/phantom/mode cttest
/pgai/hpge/centerY 0 mm
/pgai/hpge/centerZ 0 mm
/run/initialize
/vis/open OGL
/vis/drawVolume
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate
/vis/modeling/trajectories/create/drawByParticleID
/vis/scene/add/hits
/vis/viewer/set/background white 1.0
/vis/viewer/set/style surface
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/viewpointVector 0 0 1
/vis/viewer/zoom 1.4
/vis/viewer/set/autoRefresh true
